all: Process.out Producer.out Customer.out
.phony: all

Process.out: Process.c
	gcc Process.c -o Process.out

Producer.out: Producer.c
	gcc Producer.c -o Producer.out

Customer.out: Customer.c
	gcc Customer.c -o Customer.out